### ISSUE TITLE
Issues when interpreting Unicode/UTF-8 files

### ISSUE THREAD

**Issue by two-cats-in-a-trenchcoat** [ecp-lang/ecp-interpreter#14]
the ←➝➜➞➛ symbols will return a

`Traceback (most recent call last):
  File "C:\Program Files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ataylor18\AppData\Roaming\Python\Python37\site-packages\ecp\__main__.py", line 74, in <module>
    main()
  File "C:\Users\Ataylor18\AppData\Roaming\Python\Python37\site-packages\ecp\__main__.py", line 40, in main
    print(to_py_source(string))
  File "C:\Users\Ataylor18\AppData\Roaming\Python\Python37\site-packages\ecp\topython.py", line 136, in to_py_source
    code = parse_ecp(text)
  File "C:\Users\Ataylor18\AppData\Roaming\Python\Python37\site-packages\ecp\topython.py", line 109, in parse_ecp
    p = EcpParser(TokenStream(EcpLexer().lex_string(text)))
  File "C:\Users\Ataylor18\AppData\Roaming\Python\Python37\site-packages\parsergen\lexer.py", line 180, in lex_string
    token = self.getToken()
  File "C:\Users\Ataylor18\AppData\Roaming\Python\Python37\site-packages\parsergen\lexer.py", line 166, in getToken
    self.lineno, self.column, self.current_line + self.source[0]
parsergen.lexer.LexError:
  Line 1:
  ﻿
  ^
Found Unexpected character '﻿' while tokenizing!`

type error when attempting to execute a file, despite the fact that that these items are often used in official documentation
https://unicode.org/charts/PDF/U2B00.pdf could be used??

**Comment by two-cats-in-a-trenchcoat** [comment]
≠ also returns the same error
